Aleem/mentor
VillageBookBuilders/vbb-portal-web pull request #13
Opened 2022-05-13 15:22 UTC by AleemKhan12

Moved some shared interfaces and functions to utils folder and created mentor ui pages

2022-05-13 21:17 UTC, wley3337 commented on package.json
> +    "moment": "^2.29.3",
I think we want to use `luxon` for moment type stuff. Moment isn't being maintained :(

2022-05-13 21:24 UTC, wley3337 commented on src/components/mentor/MentorBooking.tsx
> +const customComponents = {
Could we rename this to something like: `calendarEventComponents` or `calendarComponents` so it's clear what it's for?

2022-05-17 22:48 UTC, wley3337 commented on src/components/mentor/MentorBookingModal.tsx
> +        // @ts-ignore
This makes me nervous :) Why do we need ts to ignore this?

2022-05-17 22:49 UTC, wley3337 commented on src/components/mentor/MentorBookingModal.tsx
> +            <Autocomplete<string, false, false, false>
This syntax feels off to me 🤔

2022-05-17 22:51 UTC, wley3337 commented on src/components/mentor/MentorBookingModal.tsx
> +              InputProps={{ startAdornment: <AccessTime /> }}
I don't understand why we're passing a component down as props here. Is this the pattern we should be following?

2022-05-17 23:08 UTC, wley3337 commented on src/components/mentor/MentorBookingModal.tsx
> +          <Box display="flex" alignItems="center">
This is of a type `string` as far as prop types. I wonder if this is what TS is complaining about. If we need CSS passed down, I think we may want to add a style prop to the Modal or just make the `tile: string | React.Node` kind of thing

2022-05-17 23:10 UTC, wley3337 commented on src/components/mentor/MentorHome.tsx
> +                You haven't booked any sessions yet. <Link to='/student/booking'>Book</Link> your sessions now!
should this be `student/booking` or should it just be `/booking` and the user context determines if it's student or mentor?

2022-05-17 23:13 UTC, wley3337 commented on src/components/mentor/MentorHome.tsx
> +    const user = useMemo(()=> getMentorProfile('1'), []);
So I'm not familiar with the `useMemo` hook and I _think_ you can use it in combination with `useSelector`. I don't know if you'd see gains in using it in this context.
Ultimately this would want to be a `useSelector(state=> state.user.mentorProfile)` here. If that feels a bit wordy to write each time, we could make a selector ( like an action creator ) for it and put it under a `redux/user/user.selectors.ts`

2022-05-17 23:15 UTC, wley3337 commented on src/components/mentor/MentorIndex.tsx
> +const MentorIndex = () => {
Do we want to establish a naming convention here for the internal routing? Not sure if we want to go Index, Controller, Router 🤷

2022-05-17 23:19 UTC, wley3337 commented on src/utils/api.ts
> +export const getAnnounements = (program?: string):Announcement[] => {
It make sense to me that an Announcement would need to be called with an id for the thing you want the announcements of. I totally forgot that this was a one to many relationship as well, so I'll add the Announcement model and include them as part of the library serializer 🤦

2022-05-17 23:20 UTC, wley3337 commented on yarn.lock
> +"moment@npm:^2.29.3":
Just a reminder not to try and edit this file when you pull moment out. Just delete it and auto generate it again with `yarn` Not that I've ever made that mistake and broken my project before.... never.

2022-05-17 23:21 UTC, wley3337 commented
Oh, don't forget to run prettier against all your files too :)

2022-05-17 23:22 UTC, geekingreen commented on src/components/mentor/MentorBookingModal.tsx
> +            <Autocomplete<string, false, false, false>
Funny enough that is the correct syntax for passing types to a component and in particular this component has some boolean values as well, which can potentially be excluded here if false is the default. `<TypeOfSearchable, Multiple, DisableClearable, FreeSolo>` are the values it is looking for, only the first is required unless props to change the three others have also been passed in

2022-05-17 23:23 UTC, geekingreen commented on src/components/mentor/MentorBookingModal.tsx
> +              InputProps={{ startAdornment: <AccessTime /> }}
This also is the correct usage of adding an adornment to a mui `TextField`

2022-05-17 23:25 UTC, wley3337 commented on src/components/mentor/MentorBookingModal.tsx
> +              InputProps={{ startAdornment: <AccessTime /> }}
Thank you!

2022-05-17 23:26 UTC, wley3337 commented on src/components/mentor/MentorBookingModal.tsx
> +            <Autocomplete<string, false, false, false>
Cool! I've never seen types passed to a component before!

2022-05-17 23:27 UTC, geekingreen commented on src/components/mentor/MentorBookingModal.tsx
> +          <Box display="flex" alignItems="center">
I made the `Modal` component in hopes that we wouldn't need to style it unless we change it as a whole. My hope is to make it as simple as possible to use, and hopefully have the styles of all modals match. So perhaps if we want titles to be centered we modify `Modal` so that all modals have centered titles?

2022-05-17 23:30 UTC, geekingreen commented on yarn.lock
> +"moment@npm:^2.29.3":
another option is to use `yarn remove <packagename>` or in this particular instance `yarn remove moment` it will remove the entry from `package.json` and update `yarn.lock` all in one go

2022-05-17 23:37 UTC, wley3337 commented on src/components/mentor/MentorHome.tsx
> +    const user = useMemo(()=> getMentorProfile('1'), []);
So it looks like [useMemo docs](https://reactjs.org/docs/hooks-reference.html#usememo) say it's used to reduce the cost of expensive tasks. I think we may want to drop it here since we're not fetching the user we're just reading it from the store

2022-05-19 02:54 UTC, geekingreen requested changes
Lookin' good, I agree with @wley3337's comments (except as noted) especially running `prettier` 😄

2022-05-21 21:45 UTC, geekingreen commented on src/components/mentor/MentorHome.tsx
> +                You haven't booked any sessions yet. <Link to='/student/booking'>Book</Link> your sessions now!
I think this is okay here since we know our context is Mentor?

2022-05-21 21:56 UTC, geekingreen commented on src/components/mentor/MentorIndex.tsx
> +const MentorIndex = () => {
I think for each main route, `/student` `/mentor` `/advisor` `/librarian`, etc... we can use `<Name>Index` (which I think we've done so far) for the sub routes, I haven't kept up a naming convention... but we could append something to make it obvious in the filename without having to dig into the `Index`'s like `<AdvisorComputersRoute />` or even just dump them into a folder called `routes` within it's context... otherwise as long as we have readable code from the index routes it should be easy enough to see what's going on

2022-05-21 21:59 UTC, geekingreen commented
@wley3337 cleaned up things a bit, let me know if there is anything else that could use a touchup. If we want to modify our convention for routes, I think we should do that in a separate PR.

2022-06-02 16:29 UTC, merged